dictionaries = []
words = [
    "advntr",
    "astro",
    "astrojs",
    "datapack",
    "dsl",
    "gitattributes",
    "gradle",
    "gradlew",
    "intelli",
    "jdk",
    "jspecify",
    "jvm",
    "keybind",
    "kts",
    "kyori",
    "learnpaperdev",
    "lifecycle",
    "mc's",
    "minimessage",
    "mkdir",
    "papermc",
    "penilla",
    "pickaxe",
    "prioritizable",
    "sdkman",
    "showlinenumbers",
    "slf",
    "webui",
    "yml",
]
flag_words = []
ignore_paths = []
ignore_patterns = []
use_global = true
